<a href="https://colab.research.google.com/github/Akshat111999/MLsummer19/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a=np.array([2,3,4,52,3])

In [3]:
type(a)


numpy.ndarray

In [0]:
b=np.array([2,3,33,32,55])

In [5]:
a


array([ 2,  3,  4, 52,  3])

In [6]:
b

array([ 2,  3, 33, 32, 55])

In [7]:
a[0]

2

In [8]:
a+b

array([ 4,  6, 37, 84, 58])

In [9]:
a+2

array([ 4,  5,  6, 54,  5])

In [10]:
a**2

array([   4,    9,   16, 2704,    9])

In [0]:
dir(np)

In [0]:
a2=a+5

In [15]:
a2

array([ 7,  8,  9, 57,  8])

In [0]:
# double dimension
x=np.array([[2,5,8],[3,6,1]])

In [17]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [18]:
x[0,0]

2

In [19]:
x[0]

array([2, 5, 8])

In [20]:
x[0,1]

5

In [0]:
y=x+7

In [23]:
y


array([[ 9, 12, 15],
       [10, 13,  8]])

In [24]:
x*2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [25]:
x**2

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [26]:
x**3

array([[  8, 125, 512],
       [ 27, 216,   1]])

In [0]:
z =np.array([ [2,7], [3,8], [2,9], [9,4]  ])

In [28]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [29]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [30]:
z.shape

(4, 2)

In [31]:
x.shape

(2, 3)

In [32]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [33]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [34]:
z[0:2]

array([[2, 7],
       [3, 8]])

In [35]:
z[0:]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [36]:
z[0:,0]

array([2, 3, 2, 9])

In [37]:
z[0:2 , 1]

array([7, 8])

In [38]:
   z[0: , 0:2]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [40]:
z[0: , [0,1]]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [41]:
x[0: , [0,2]]

array([[2, 8],
       [3, 1]])

In [42]:
z[[0,2],0]

array([2, 2])

In [44]:
x[0: ,[0,2]]

array([[2, 8],
       [3, 1]])

In [45]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [46]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [47]:
z[[0,3],1]

array([7, 4])

In [0]:
b=np.array( [[1,9,7], [3,2,8], [4,5,6], [2,9,0]] )

In [55]:
b

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [56]:
b[0:, 1]

array([9, 2, 5, 9])

In [57]:
b[[0],2 ]

array([7])

In [58]:
b[1:4,2]

array([8, 6, 0])

In [59]:
b[1: , [0,1]]

array([[3, 2],
       [4, 5],
       [2, 9]])

In [60]:
b

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [61]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [62]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
x1=x.reshape(3,2)

In [66]:
x1

array([[2, 5],
       [8, 3],
       [6, 1]])

In [67]:
 np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [70]:
 np.zeros((3,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [71]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
#for writing specific number
np.full((4,5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [73]:
[i  for i in dir(np)  if 'random' in i]

['random']

In [0]:
del matplotlib